### PR TITLE
Add support for eth_signTypedData_v4

### PR DESCRIPTION
**Pull request by dmihal**
Add's support for the `eth_signTypedData_v4` RPC method. Also supports signing typed data where the payload is a string (which is how many nodes expect it).

### CODE REVIEW

**Comment by davidmurdoch** [comment]
@dmihal do you know of nodes that have implemented `eth_signTypedData` and/or `eth_signTypedData_v4`?

**Comment by dmihal** [comment]
@davidmurdoch Looks like Geth has eth_signTypedData, but not eth_signTypedData_v4

However, metamask includes eth_signTypedData_v4

**Comment by gnidan** [comment]
Hey @dmihal sorry to drop the ball on this. Do you know if the situation around this method has changed at all? Does geth support it yet (e.g.)?

Regardless, for this PR, it might make sense to target `develop` now, which represents the upcoming Ganache v7.0.0 release. We _could_ get this into the existing major release, but we _are_ seeking to move forward.

Also it might be worth noting that it's been a long time since August of last year; this v4 method might already exist but without the `_v4` suffix. Sounds like we'll need to do some investigation.

Thanks!

**Comment by dogutaskiran** [comment]
Any updates on getting this into the build?

**Comment by davidmurdoch** [comment]
Released in https://github.com/trufflesuite/ganache/releases/tag/ganache%407.0.0-alpha.2

**Pull request closed without merging**
