### PR TITLE
Add `balances` option to set default account balances

### PR DESCRIPTION
**Pull request by IstoraMandiri**
https://github.com/ethereumjs/testrpc/issues/265

### CODE REVIEW

**Comment by benjamincburns** [comment]
@hitchcott this change looks fine, but can you please add a test for this?

**Comment by benjamincburns** [comment]
@hitchcott I've gone ahead and added the test myself. Thanks for the contribution!

**Comment by cbruguera** [comment]
@benjamincburns @hitchcott How does this work? How do I get my test accounts to initialize with an arbitrary amount of ETH?... Are there any docs on this?

**Comment by benjamincburns** [comment]
@cbruguera have a look at the `README.md` in `ganache-core` and `ganache-cli`.

Until I have a chance to release `ganache-core`, you'll have to build your own `ganache-cli` by cloning it and `ganache-core`, then using `npm link` to build `ganache-cli` against your local `ganache-core`.

**Pull request merged**
