### PR TITLE
Add polyfill for http and https

### PR DESCRIPTION
**Pull request by rmeissner**
Contributes to https://github.com/trufflesuite/ganache/issues/1245

Changes:
- sets `http` polyfill to `stream-http`
- sets `https` polyfill to `https-browserify`

Notes:
- `isomporphic-ws` was already set

### CODE REVIEW

**Comment by rmeissner** [comment]
I tested this by using ganache in a react app. I worked well with the dev server, but if I perform a production optimized build I get a compiler error `TypeError: /ganache/src/packages/ganache/dist/web/ganache.min.js: Duplicate declaration "a"` ... not sure why.

**Comment by rmeissner** [comment]
I couldn't get the URL error fixed easily. Any idea how to go at this? I thought I can polyfill this, but it doesn't work and now I was thinking about using a wrapper library such as `native-url`, but then the used type definitions don't work in all places out of the box :(

**Comment by davidmurdoch** [comment]
The browser has a native `URL` support, so I'm not sure what's going on with that. I'll take a closer look at this today.

**Comment by rmeissner** [comment]
Yes. I found an article that it should be possible just to remove the import. But this doesn't work in all places (it does in some)

**Comment by davidmurdoch** [comment]
We're finally getting this working. Thanks for starting it! I've moved the work from this PR over to #3130 so I can finish up the work on a branch based on this repository. See: #3130!

**Pull request closed without merging**
