### PR TITLE
test: replace `assert.equal` with `assert.strictEqual` in tests

### LINKED ISSUE #3504: chore: check for cases where `assert.equal` is used where `assert.strictEqual` is preferred in unit tests

### PR DESCRIPTION
**Pull request by predetermined**
Fixes #3504

### CODE REVIEW

**Review by MicaiahReid — APPROVED** [review]

**Comment by MicaiahReid** [comment]
Thanks for the PR, @l2ig!

**Review by jeffsmale90 — APPROVED** [review]

**Comment by jeffsmale90** [comment]
Nice! I love consistency :)

**Review by davidmurdoch — APPROVED** [review]
@l2ig, thanks for doing this! Would you like to tackle #3530 as well? :-D

**Comment by davidmurdoch** [comment]
Note: I've updated the PR title to use the `test: ` prefix as this change "corrects existing tests".

**Pull request merged**
