### PR TITLE
docs: update README.md to clarify usage

### PR DESCRIPTION
**Pull request by emilyJLin95**
Just clarifying how to run Ganache for usage on the CLI as well as in programmatic usage.

### CODE REVIEW

**Comment by davidmurdoch** [comment]
The section you're updating is about adding `ganache` to an _npm_ project (it gets added to their `package.json` as a dependency).

There is already a section in the README.md about command line use that says:


> Once installed globally, you can start ganache right from your command line:

```bash
$ ganache
Ganache CLI v6.12.1 (ganache-core: 2.13.1)
```

I welcome improvements to the readability here so it is more clear on the different ways ganache can be used.

**Comment by emilyJLin95** [comment]
ah okay updated section titles

also, just wondering, is line 50 still up to date? do we support node v12

@davidmurdoch

**Comment by davidmurdoch** [comment]
> ah okay updated section titles
> 
> also, just wondering, is line 50 still up to date? do we support node v12
> 
> @davidmurdoch

Yes, Ganache still works with v12.0.0+. This will be changing soon though.

**Review by davidmurdoch — APPROVED** [review]

**Review by eggplantzzz — APPROVED** [review]
I like

**Review by tenthirtyone — APPROVED** [review]

**Pull request merged**
